apiVersion: v1
kind: Service
metadata:
  name: langfuse-clickhouse-shard0
  namespace: langfuse
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: langfuse
  ports:
    - name: native
      port: 9000
      targetPort: 9000
